name: GitHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug:

    runs-on: ubuntu-latest
    container: heltai/dealii:vscode

    steps:
    - uses: actions/checkout@v2
    
    - name: Build lab 01
      run: |
         cd labs/lab-01
         rm -rf build_linux_debug
         mkdir build_linux_debug 
         cd build_linux_debug
         cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug; ninja
    - name: Run gtest on lab 01 
      run: |
         cd labs/lab-01/build_linux_debug
         ./gtest
    
    - name: Build lab 02
      run: |
         cd labs/lab-02
         rm -rf build_linux_debug
         mkdir build_linux_debug 
         cd build_linux_debug
         cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug; ninja
    - name: Run gtest on lab 02 
      run: |
         cd labs/lab-02/build_linux_debug
         ./gtest

    - name: Build lab 03
      run: |
         cd labs/lab-03
         rm -rf build_linux_debug
         mkdir build_linux_debug 
         cd build_linux_debug
         cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug; ninja
    - name: Run gtest on lab 03 
      run: |
         cd labs/lab-03/build_linux_debug
         ./gtest